
services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx_container
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    networks:
      - my_network

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress_container
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./requirements/wordpress:/var/www/html
    networks:
      - my_network

  db:
    build:
      context: ./requirements/mariadb
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:

