services:

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - webnet
    restart: always
    expose:
      - "3306"

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - webnet

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - webnet
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always

  adminer:
    build:
      context: ./requirements/bonus/adminer
    container_name: adminer
    volumes:
      - adminer_data:/var/www/html
    ports:
      - "8080:8080"
    networks:
      - webnet
  ftp:
    build:
      context: ./requirements/bonus/ftp
    container_name: ftp
    env_file:
      - .env
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    volumes:
      - wordpress_data:/var/ftp
    networks:
      - webnet
    restart: always

  redis:
    build:
      context: ./requirements/bonus/redis
    container_name: redis
    ports:
      - 6379
    volumes:
      - redis_data:/data
    networks:
      - webnet
    restart: always

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rdelicad/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rdelicad/data/mariadb
  adminer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rdelicad/data/adminer
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rdelicad/data/redis

networks:
  webnet:
    driver: bridge

