FROM debian:bullseye

RUN set -eux; \
  apt-get update; \
  mkdir -p /var/www/html && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
	php \
  php-fpm \
  php-mysql \
	wget \
  tar

COPY /tools/init.sh .
COPY /tools/inception_page.html /var/www/html/inception_page.html

EXPOSE 9000

RUN chmod +x init.sh
CMD ["sh", "init.sh"]

